import Footer from './components/shared/Footer'
import Navbar from './components/shared/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Learning NExt',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Navbar></Navbar>
      <body className={inter.className}>{children}</body>
      <Footer/>
    </html>
  )
}
